FROM rocker/r-ver:latest

LABEL org.opencontainers.image.authors="us@couchbits.com"
LABEL org.opencontainers.image.vendor="couchbits GmbH"

ENV PROJECT_DIR=/moveapps-r-sdk
ENV RENV_PATHS_CACHE=/renv/cache

RUN apt-get update && apt-get install -y \
    libabsl-dev \
    libcurl4-openssl-dev \
    libgdal-dev \
    libssl-dev \
    libudunits2-dev \
    libxml2-dev \ 
    && rm -rf /var/lib/apt/lists/*

# Create the project directory
RUN mkdir -p $PROJECT_DIR

# Set the working directory
WORKDIR $PROJECT_DIR

# Install renv and restore packages
COPY renv.lock ./
RUN R -e 'install.packages("renv")' && \
    R -e 'renv::consent(provided = TRUE); renv::restore()' && \
    R -e 'renv::clean()'
    
RUN R -e 'if (!requireNamespace("testthat", quietly=TRUE)) install.packages("testthat")'

# Copy necessary files
COPY data/ ./data/
COPY tests/ ./tests/
COPY RFunction.R ./

CMD ["bash"]
